# Generated by Django 6.0.1 on 2026-01-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_donationdetails_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managementteam',
            options={'ordering': ['name'], 'verbose_name': 'Management Team Member', 'verbose_name_plural': 'Management Team'},
        ),
        migrations.RemoveField(
            model_name='managementteam',
            name='order',
        ),
    ]
