# Generated by Django 6.0.1 on 2026-01-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_remove_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationdetails',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='donation_proofs/'),
        ),
    ]
