# Generated by Django 6.0.1 on 2026-01-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_donationdetails_screenshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
