# Generated by Django 6.0.1 on 2026-01-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_alumnievent_alumniprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Download',
        ),
    ]
