# Generated by Django 6.0.1 on 2026-01-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_delete_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
