# Generated by Django 6.0.1 on 2026-01-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_alter_alumniprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnievent',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
