# Generated by Django 6.0.1 on 2026-01-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_alumnievent_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationdetails',
            name='amount',
        ),
    ]
