# Generated by Django 6.0.1 on 2026-01-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_remove_donationdetails_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementteam',
            name='bio',
        ),
    ]
