# Generated by Django 6.0.1 on 2026-01-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_remove_managementteam_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
    ]
