# Generated by Django 6.0.1 on 2026-01-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_remove_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
    ]
